# Generated by Django 3.2.7 on 2021-10-03 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 11, 21, 409106)),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 11, 21, 409106)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 11, 21, 409106)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_id', to='books.book'),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 11, 21, 409106)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='get_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 11, 21, 411127)),
        ),
        migrations.AlterField(
            model_name='kartoteka',
            name='return_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 12, 11, 21, 411127)),
        ),
        migrations.AlterField(
            model_name='reader',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 11, 21, 409106)),
        ),
    ]
